core:
  max_concurrency: 35
  initial_concurrency: 3
  initial_step: 5

http:
  requests_timeout_seconds: 5
  cookies_refresh_delay: 600    # 10 minutes
  max_rate_limits_per_second: 3
  rate_limit_wait_seconds: 3

  step_data:
    min_time_since_last_adjustment_milli: 100
    max_error_deviation: 1
    max_consecutive_errors: 3
    max_retries: 5
    max_time: 1000
    aggressive_time: 800
    medium_time: 500
    min_time: 300
    retry_time: 300
    last_delay_offset: 300
  
  concurrency_data:
    min_time_since_last_adjustment_milli: 100
    max_error_deviation: 1
    min_concurrency: 3
    max_time: 500
    medium_time: 350
    min_time: 300

standard:
  urls:
    base_url: "https://url"
    items_url: "https://url/items"
    item_url: "https://url/items/<item_id>"         # Remove <item_id>, leave "/"
    item_url_after_id: "<item_id>/additional/info"  # Remove <item_id>, leave "/"
    randomize_item_url_addition: true
  items_response:
    items: "json_items_key_in_response"
    id: "json_id_key_in_each_item_in_items"
  item_response:
    item: "json_item_key_in_response"
    timestamp: "json_timestamp_key_in_item"
  session_cookie_name: "cookie_name"
  timestamp_format: "item_timestamp_format"
  initial_delay: 1000000