core:
  thresholds_initial_amount(max_255): 10
  expected_max_thresholds_amount(max_255): 100
  thresholds_offset(max_255): 50

http:
  requests_timeout_seconds: 5
  cookies_sessions_amount: 5
  cookies_refresh_delay: 600    # 10 minutes
  crash_on_first_cookie_fetch_error: true
  max_retries_per_item: 5
  delay_between_retries_milli: 100
  max_rate_limits_per_second: 3
  rate_limit_wait_seconds: 3

standard:
  urls:
    base_url: "https://url"
    items_url: "https://url/items"
    item_url: "https://url/items/<item_id>"         # Remove <item_id>, leave "/"
    item_url_after_id: "<item_id>/additional/info"  # Remove <item_id>, leave "/"
    randomize_item_url_addition: true
  items_response:
    items: "json_items_key_in_response"
    id: "json_id_key_in_each_item_in_items"
  item_response:
    item: "json_item_key_in_response"
    timestamp: "json_timestamp_key_in_item"
    item_when_url_suffix: "json_item_key_in_response_when_item_url_addition"
    timestamp_when_url_suffix: "json_timestamp_key_in_item_when_item_url_addition"
  websocket:
    ws_urls:
      - "ws://<host1>:<port1>/<path1>"
      - "ws://<host2>:<port2>/<path2>"
      - "ws://<host3>:<port3>/<path3>"
    ws_headers:
      header_name1: "header_value1"
      header_name2: "header_value2"
      header_name3: "header_value3"
  session_cookie_names:
    - "cookie_name1"
    - "cookie_name2"
    - "cookie_name3"
  timestamp_format: "item_timestamp_format"
  initial_delay: 1000000

thresholds_adjustment_policies:
  - percentage: 0.9
    compute_increment: "NewTimestamp >= CurrentTimestamp+500 ? max(ThresholdsAmount * 0.25, 2) : 1"
  - percentage: 0.5
    compute_increment: "0"
  - percentage: 0.3
    compute_increment: "-1"
  - percentage: 0
    compute_increment: "-0.25 * ThresholdsAmount"