FROM golang:1.23.0 as builder
WORKDIR /usr/src/crawler

COPY go.mod .
COPY go.sum .
RUN go mod download && go mod verify

COPY app/pkg ./app/pkg
COPY app/cmd ./app/cmd

RUN go build -v -o /run-app ./app/cmd/crawler/main.go

FROM ubuntu:22.04
WORKDIR /usr/src/crawler

COPY config.yml* ./
COPY app/assets ./app/assets

COPY --from=builder /run-app /usr/local/bin/

RUN apt-get update && apt-get install -y ca-certificates

CMD ["/bin/bash", "-c", "run-app &> /usr/src/crawler/log/logs.log"]